;Config File for PCEDX NamocoG - XBLA - 0x58410A8C

;Do not use space in the Var define line, eg:
;varA = 123 (WRONG)
;varA=123   (RIGHT)

;id0 target product id: like 58410A8C, 0 means do not jump to Market
id0=0

;url
url=http://ng.namco-ch.net/

;END